### ISSUE TITLE
Feature Request: Open server url in new window by Ctrl+Left Click or by Middle Click on the server icon

### ISSUE THREAD

**Issue by amerhanna** [easypanel-io/hub#1]
Surround the server icon with <a> tag wuth the server url

<a href={server.url} target="_blank" onClick={(e)=>{e.preventDefault()}}>
</a>

![image](https://github.com/user-attachments/assets/e7d242c0-a5ae-4ca5-9951-badfa5e86cf6)

**Comment by deiucanta** [comment]
Done, thanks for the suggestion
